[2024-03-23T01:18:03.733+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_team_standings.extract_team_standings scheduled__2024-03-21T13:00:00+00:00 [queued]>
[2024-03-23T01:18:03.741+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_team_standings.extract_team_standings scheduled__2024-03-21T13:00:00+00:00 [queued]>
[2024-03-23T01:18:03.741+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 3
[2024-03-23T01:18:03.749+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): extract_team_standings> on 2024-03-21 13:00:00+00:00
[2024-03-23T01:18:03.754+0000] {standard_task_runner.py:60} INFO - Started process 367 to run task
[2024-03-23T01:18:03.760+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'get_team_standings', 'extract_team_standings', 'scheduled__2024-03-21T13:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/team_stats.py', '--cfg-path', '/tmp/tmpt_4tpcby']
[2024-03-23T01:18:03.765+0000] {standard_task_runner.py:88} INFO - Job 7: Subtask extract_team_standings
[2024-03-23T01:18:03.824+0000] {task_command.py:423} INFO - Running <TaskInstance: get_team_standings.extract_team_standings scheduled__2024-03-21T13:00:00+00:00 [running]> on host e4a45e6f747a
[2024-03-23T01:18:03.884+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='jmc' AIRFLOW_CTX_DAG_ID='get_team_standings' AIRFLOW_CTX_TASK_ID='extract_team_standings' AIRFLOW_CTX_EXECUTION_DATE='2024-03-21T13:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-21T13:00:00+00:00'
[2024-03-23T01:18:04.200+0000] {base_aws.py:581} WARNING - Unable to find AWS Connection ID 'aws_default', switching to empty.
[2024-03-23T01:18:04.200+0000] {base_aws.py:161} INFO - No connection ID provided. Fallback on boto3 credential strategy (region_name=None). See: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html
[2024-03-23T01:18:04.443+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2024-03-23T01:18:05.721+0000] {python.py:202} INFO - Done. Returned value was: nba_logs/team_standings_20240321.csv
[2024-03-23T01:18:05.782+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=get_team_standings, task_id=extract_team_standings, execution_date=20240321T130000, start_date=20240323T011803, end_date=20240323T011805
[2024-03-23T01:18:05.841+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-23T01:18:05.873+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/models/baseoperator.py:1201 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2024-03-23T01:18:05.890+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
